### ISSUE TITLE
Axis merge: Greatest does not seem to work properly

### ISSUE THREAD

**Issue by WooterTheTroubleshooter** [evilC/AHK-Universal-Joystick-Remapper#13]
On tab 1 I have set a pedal to Split L, which shows the correct output from 0 to 100%
On tab 2 I have set a throttle stick to greatest and inverted it because the throttle is facing the wrong way.

When I move the throttle up I would expect it's state to become visible in the vjoy monitor, but it does not become visible until the axis is at 100%, when I leave the throttle at 0% using the pedal does not allow the merged axis to go higher than 50%.

With the description in the tooltip for the merge options I would expect the highest of the 2 axis to become the resulting output.

**Comment by evilC** [comment]
Split and greatest were not meant to be used together.

Split is for when you are using one axis (it maps the full range of the output to half the input).

Try removing the split option.
You may need to fiddle with the invert options for each axis to get them to work together right.

Does this solve your problem?

**Comment by WooterTheTroubleshooter** [comment]
If I remove the split the output will always rest in the middle as the axis
is shared between 2 pedals. To use the pedal separately I need to use the
split. Would it be possible to use the output of tab 1 instead of the raw
input?

**Comment by evilC** [comment]
ahh, my pedals are two separate axes, that would explain things.

I guess it is probably possible, I would have to look at the code.
So what, you want one axis where one of your pedals controls one side, and the throttle unit controls the other?

**Comment by evilC** [comment]
In order for me not to go changing things and getting it wrong, can we establish exactly what your expected behavior is?

DEFINITIONS
So, assuming the output axis is the Y axis...
We shall call centered 50%, bottom as 0%, top as 100%

INPUTS
Pedal (Rests at 50%), fully pressing pedal is 100% of input
Throttle - obvious, 0% is full towards you, 100% is full away from you.

OUTPUT LOGIC
What do you want?
Pedal 50% (idle), Throttle 0% = ? Output @ 50% ?
Pedal 100%,  Throttle 0% = ? Output @ 100% ?
Pedal 50% (idle), Throttle 100% = ? Output 0% ?

**Comment by WooterTheTroubleshooter** [comment]
My throttle is actually inverted so when it's full towards me it's at 100%
when I activate invert it gets set to 0% when it's fully towards me.

Personally I would expect the merge to use the output of tab1 so al
specialties can be used for the merge system.

Definitions:
Throttle below has inverted option on

Output:
Pedal(50%) output of tab1(0%)
throttle(0%) output of tab2 (0%) greatest is 0%

Pedal(75%) output of tab1(50%)
Throttle(0%) output of tab2(0%)
Greatest is (50%)

Pedal(75%) output of tab1(50%)
Throttle(60%) output of tab2(60%)
Greatest is (60%)

Pedal(75%) output of tab1(50%)
Throttle(100%) output of tab2(100%)
Greatest is (100%)

Pedal(100%) output of tab1(100%)
Throttle(50%) output of tab2(50%)
Greatest is (100%)
 Op 15 jul. 2015 15:43 schreef "Clive Galway" <notifications@github.com>
het volgende:

**Comment by evilC** [comment]
Right, I just sat down and spent tome serious time examining exactly how the merge modes work, and clearly I was drunk or something when I wrote Greatest mode...

*Merge* mode works logically - the slider on Tab 1 is the "low" part of the scale, and the right end of the slider is the middle of the output scale. The slider on Tab 1 should "rest" at the right end when there is no input.  
The slider on Tab 2 is the "high" part of the scale, and the left end of that slider is the middle of the output scale. The slider on Tab 2 should rest at the left end when there is no input.  

If the two axes are used together, one cancels the other out.  
This seems sensible and logical to me - do you agree?  

But then *Greatest* mode seems to completely throw that model out of the window.  
It should work the same way, with the only difference being that instead of averaging out the two inputs, it looks at whichever is furthest from the "center", and behaves as if the other one is not pressed at all.  

I have coded a test version that changes how *Greatest* mode works, please give it a try and tell me if this now works as you expect.  

http://evilc.com/files/ahk/vjoy/ujr.exe

**Comment by evilC** [comment]
Please be aware that for the moment, the *Deadzone* setting does not work properly in combination with Split L/H.  
This would require further work.

**Comment by WooterTheTroubleshooter** [comment]
I agree the merge works like expected. Also I must add that for the throttle I was only thinking of a linear axis, this might cause some confusion.

I have tested the version you posted, however even with the description above, with a joystick axis and the throttle which makes testing easy. It does not look like the most out-of-center slider is the result value shown in vJoy monitor.
If I put the throttle anywhere under 100% the joystick determines the output, if I put the throttle to 100% the throttle the output is and remains 100%.
Also when I put the throttle to 0% with the joystick axis centered, I still get some output in the vjoy monitor, I would now expect to have 0% output with that axis.

My original expectation was based on 0 to 100% and the greatest is the output value. That is also what I need to use the pedal and the throttle together for throttle axis, so when I'm flying a 'vtol' and landing I am able to make quicker adjustments to the throttle then when I'm flying normally.

**Comment by evilC** [comment]
Still having trouble fully understanding what you want...  
Maybe understanding the use case will help me...  
So the output axis is to be used to control the throttle for a VTOL craft?  
And you want to use a throttle and a trigger on a joypad as two alternate ways to control the throttle?  
Whichever is depressed the most sets the output for the throttle?

**Comment by evilC** [comment]
I uploaded a [new test version](http://evilc.com/files/ahk/vjoy/ujr.exe) and added a new merge mode which I called "Wooter" for now.  
Is that what you wanted?

**Comment by WooterTheTroubleshooter** [comment]
That is exactly what I described.

I do want to note however that the greatest setting itself is still functioning somewhat strange. And I cannot reproduce the below description for it:
"
>It should work the same way, with the only difference being that instead of averaging out the two inputs, it looks at whichever is furthest from the "center", and behaves as if the other one is not pressed at all.
"

**Comment by evilC** [comment]
Hallelujah! We finally got there :)

Both Merge and Greatest are meant to combine two axes into one that is centered in the middle.  

Imagine an axis where the left side of it is tab 1 and the right side is tab 2.  

```
|__Tab 1 Slider ___|___ Tab 2 Slider __|
```

The output axis defaults to the **middle**.  
The more the slider on tab 1 is to the left, it pulls the output left.  
The more the slider on tab 2 is to the right, it pulls the output right.  

With Merge mode, if tab 1 is pulling the output left and tab 2 is pulling the output right, then they cancel each other out.
So if you move tab 1 slider 50% left, and tab 2 slider 60% right, the net result is that the output is 10% right.

With Greatest mode, they do not cancel each other out - whichever slider is further from the mid point, it takes precedence. So in the same example as above, the output would be 60% right instead of 10% right.

Merge and greatest mode were designed for racing pedals where each pedal is it's own axis - it allows you to merge two racing pedal axes into one "Rudder" axis.

So with the racing pedal use case in mind - no pedals pressed = output is in the middle (No rudder).
Just the left pedal pressed half way, the rudder goes to half left.
Just the right pedal pressed half way, the rudder goes to half right.

If you press the left pedal 50% and the right pedal 60%...
Merge mode = rudder is 10% right.
Greatest mode = rudder is 60% right.

I really probably need to come up with some documentation to explain all this...

**Comment by evilC** [comment]
6.7 has been released with the new mode, which I called "Linear".
Please let me know if it all still works, and I will close this ticket.

**Comment by WooterTheTroubleshooter** [comment]
Ok, your explanation makes sense as it thought greatest would have worked like 2 overlapping axes whichever is more excentric(based on mid), is the output value

**Comment by WooterTheTroubleshooter** [comment]
Thanks for adding this feature :) It works great with my application.
